### ISSUE TITLE
Wrong title and github repo in the audit report

### ISSUE THREAD

**Issue by Kaiziron** [StackingDAO/app#1]
https://github.com/StackingDAO/app/blob/master/Audit-2023-11.pdf
<img width="515" alt="image" src="https://github.com/StackingDAO/app/assets/16369212/6b377fca-2721-4533-bd5e-2f3a7f6129b5">
<img width="732" alt="image" src="https://github.com/StackingDAO/app/assets/16369212/97a7729b-74cf-4e05-a247-aad7a78f1caa">

It has a title of Arkadiko Audit, which is another audit coinfabrik did. Also the git repository link is wrong.

This is the correct report :
https://www.coinfabrik.com/wp-content/uploads/2023/12/Stacking-DAO-Audit-2023-11.pdf

**Comment by philipdesmedt** [comment]
Done, thanks for this. The repo we'll try open-sourcing soon!
